const EVENTS = {
  connection: "connection",
  disconnect: "disconnect",
  CLIENT: {
    CREATE_LOBBY: "CREATE_LOBBY",
    SEND_LOBBY_MESSAGE: "SEND_LOBBY_MESSAGE",
    JOIN_LOBBY: "JOIN_LOBBY",
    LEAVE_LOBBY: "LEAVE_LOBBY",
    GET_LOBBY_INFO: "GET_LOBBY_INFO",
    CHECK_USERNAME: "CHECK_USERNAME"
  },
  SERVER: {
    LOBBYS: "LOBBYS",
    JOINED_LOBBY: "JOINED_LOBBY",
    LOBBY_MESSAGE: "LOBBY_MESSAGE",
    JOINED_LOBBY_USER: "JOINED_LOBBY_USER",
    LEAVE_LOBBY: "LEAVE_LOBBY",
    QUEUE: "QUEUE",
    LOBBY_FULL: "LOBBY_FULL",
    LOBBY_USERS_LIST: "LOBBY_USERS_LIST",
    CHECK_USERNAME_EXISTS: "CHECK_USERNAME_EXISTS",
    CHECK_USERNAME: "CHECK_USERNAME"
  },
};

export default EVENTS;
